services:
  autobahndata:
    container_name: autobahndatacontainer
    build: .
    image: autobahndata:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge